---
# Main playbook to set up and install Helm, Cert-Manager, Traefik, and Rancher

- name: Setup RKE2 Management Cluster Server
  hosts: 
   - rke2_server_agents
   - rke2_worker_agents
  become: true
  roles:
    - common
    - ha-rke2-server

- name: Setup and Install Helm, Cert-Manager, Traefik, and Rancher
  hosts: server_agent_1
  become: true
  roles:
    - helm
    - helm_plugins
    - cert_manager
    - rancher