---
# Cert-Manager tasks

- name: Check if kubectl can reach the cluster before proceeding
  shell: |
    export KUBECONFIG={{ kubectl_config }}
    /var/lib/rancher/rke2/bin/kubectl get nodes
  register: kubectl_status
  failed_when: kubectl_status.rc != 0
  changed_when: false
  retries: 10
  delay: 5
  until: kubectl_status.rc == 0
  when: self_signed_cert == false
  
- name: Add Cert-Manager Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present  # Ensure repository is added
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable
  when: self_signed_cert == false

- name: Deploy Cert-Manager chart inside cert-manager namespace
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: "{{ cert_manager_chart_ref }}"
    chart_version: "{{ cert_manager_chart_version }}"
    release_namespace: cert-manager
    update_repo_cache: true
    create_namespace: true
    state: present
    wait: true
    values:
      installCRDs: true  # Additional values to install CRDs
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable
  when: self_signed_cert == false